//AUTH
export const LOGINUSERSUCCESS = "LOGINUSERSUCCESS";
export const LOGINUSERFAILED = "LOGINUSERFAILED"; 
export const LOGOUTUSER = "LOGOUTUSER";

//HOSTINPUTES
export const CHANGEINPUTHANDLER = "CHANGEINPUTHANDLER";
export const RESERINPUTHANDLER = "RESERINPUTHANDLER";